<x-layout>
    <h1>契約書</h1>
    <nav>
        <ul>
            <li>□新規仏壇</li>
            <li>□修理仏壇</li>
            <li>□仕切書</li>
        </ul>
        <ul>
            <li>□福井店</li>
            <li>□大野店</li>
            <li>□鯖江店</li>
            <li>□坂井店</li>
        </ul>
    </nav>
    <div class="head_container">
        <ul>
            <li class="ht60">
                <span>御氏名</span>
                <p></p>
            </li>
            <li class="ht60">
                <span>御住所/TEL</span>
                <p></p>
            </li>
        </ul>
        <ul>
            <li>
                <span>宗派</span>
                <p></p>
            </li>
            <li>
                <span>所属寺</span>
                <p></p>
            </li>
            <li>
                <span>仏壇</span>
                <p></p>
            </li>
            <li>
                <span>寸法</span>
                <p></p>
            </li>
            <li>
                <span>担当</span>
                <p></p>
            </li>
        </ul>
        <ul>
            <li>
                <span>契約日</span>
                <p></p>
            </li>
            <li>
                <span>納品予定</span>
                <p></p>
            </li>
            <li>
                <span>納品実績</span>
                <p></p>
            </li>
            <li>
                <span>引取予定</span>
                <p></p>
            </li>
        </ul>
        <ul>
            <li>
                <span>受注金額</span>
                <p></p>
            </li>
            <li>
                <span>消費税</span>
                <p></p>
            </li>
            <li>
                <span>御支払総額</span>
                <p></p>
            </li>
        </ul>
    </div>
    <div class="sertch_container">
        <div class="left_content">
            <label>
                商品No
                <input type="text" name="">
            </label>
        </div>
        <div class="right_content">
            <span>
                <a href="">仏壇追加</a>
            </span>
            <span>
                <a href="">仏具追加</a>
            </span>
        </div>
    </div>
    <div class="info_container">
        <ul>
            <li>
                <span>商品名</span>
                <p></p>
            </li>
            <li>
                <span>サイズ</span>
                <p></p>
            </li>
            <li>
                <span>仏間</span>
                <p></p>
            </li>
        </ul>
    </div>
    <table>
        <thead>
            <tr>
                <th>内容</th>
                <th>金額</th>
                <th>仏具個別No</th>
                <th>仏具品名</th>
                <th>仏具金額</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>本体内容</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>仏具</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>お焚き上げ</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>消費税</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>合計金額</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td colspan="2">御支払い</td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>前受金</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>中間金</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>残金</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </tbody>
            <tr>
                <td colspan="5">備考</td>
            </tr>
            <tr>
                <td colspan="5" class="note"></td>
            </tr>
        <tfoot>
        </tfoot>
    </table>
    <div class="store_container">
        <ul class="store_info">
            <span>店舗情報</span>
            <li>
                <span>福井総本店</span>
                <span>福井市米松2-24-36</span>
                <span>(0776)54-1933</span>
            </li>
            <li>
                <span>大野本店</span>
                <span>大野市元町7-16</span>
                <span>(0779)66-1932</span>
            </li>
            <li>
                <span>鯖江インター店</span>
                <span>鯖江市東鯖江2-202</span>
                <span>(0778)52-5413</span>
            </li>
            <li>
                <span>坂井店</span>
                <span>坂井市坂井町上新庄2-24-3</span>
                <span>(0776)72-1938</span>
            </li>
        </ul>
        <ul class="payment_info">
            <span>振込先</span>
            <li>
                <span>福井総本店</span>
                <span>福井銀行さくら通り支店(普)</span>
                <span>No.159920</span>
                <span>(株)KBB</span>
            </li>
            <li>
                <span>大野本店</span>
                <span>北陸銀行大野支店(普)</span>
                <span>No.4182050</span>
                <span>(株)KBB</span>
            </li>
            <li>
                <span>鯖江インター店</span>
                <span>福井銀行東鯖江支店(普)</span>
                <span>No.1022671</span>
                <span>(株)KBB</span>
            </li>
            <li>
                <span>坂井店</span>
                <span>福井銀行坂井町支店(普)</span>
                <span>No.1082236</span>
                <span>(株)KBB</span>
            </li>
        </ul>
    </div>
    <div class="foot_title">
        かじそ仏壇
    </div>
</x-layout>
